server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: minio-demo
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.11.128:13306/leohou?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root

#请把下面的配置换成自己的服务器
minio:
  endpoint: http://192.168.11.128:19000
  accessKey: minioadmin
  secretKey: minioadmin
  filHost: ""

logging:
  level:
    ROOT: INFO
    com.minio: DEBUG
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{50} - %msg%n'
  file:
    name: ${logging.file.path}/${spring.application.name}.log
    path: /home/logs/${spring.application.name}
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
